version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags: []
  go: "1.25"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - exhaustive
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - depguard
    - exhaustruct
    - gochecknoglobals
    - lll
    - wsl

issues:
  exclude:
    - path: _test\.go
      linters:
        - gocognit
        - goconst
        - gocyclo
        - gomnd
    - path: internal/modules/assistant/
      linters:
        - gocognit
    - linters:
        - gosec
      text: "G104"

output:
  format: colored-line-number