version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags: []
  go: "1.25"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - exhaustive
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - depguard
    - exhaustruct
    - gochecknoglobals
    - lll
    - wsl
  settings:
    gocognit:
      min-complexity: 50
    goconst:
      min-len: 3
      min-occurrences: 3
    errcheck:
      check-type-assertions: true
      check-blank: false