package notifications

import (
	"time"

	"github.com/google/uuid"
)

const (
	TypeLowStock    = "low_stock"
	TypeCreditLimit = "credit_limit"

	SeverityInfo     = "info"
	SeverityWarning  = "warning"
	SeverityCritical = "critical"
)

// Notification is a persisted, per-business alert. It is generated by the
// background scheduler (low stock, credit limits) rather than on request.
type Notification struct {
	ID         uuid.UUID  `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	BusinessID uuid.UUID  `gorm:"type:uuid;index;not null" json:"business_id"`
	UserID     *uuid.UUID `gorm:"type:uuid;index" json:"user_id,omitempty"`
	Type       string     `gorm:"not null" json:"type"`
	Severity   string     `gorm:"not null;default:info" json:"severity"`
	Recipient  string     `gorm:"not null;default:''" json:"recipient"`
	Title      string     `gorm:"not null;default:''" json:"title"`
	Message    string     `gorm:"not null;default:''" json:"message"`
	EntityID   *uuid.UUID `gorm:"type:uuid" json:"entity_id,omitempty"`
	EntityName string     `gorm:"not null;default:''" json:"entity_name"`
	Read       bool       `gorm:"column:is_read;not null;default:false" json:"read"`
	CreatedAt  time.Time  `json:"created_at"`
}

func (Notification) TableName() string { return "notifications" }
