import Link from "next/link";
import { ArrowRight, BarChart3, Boxes, Brain, Check, CircleDollarSign, ShieldCheck, Sparkles, Store, Users } from "lucide-react";

const features = [{ icon: Boxes, title: "Know your stock", text: "See what is moving, what is low, and what needs ordering before a customer asks." }, { icon: CircleDollarSign, title: "Know your numbers", text: "Sales, expenses, profit, credit and cash flow in one clear view." }, { icon: Brain, title: "Ask your business", text: "Tell the assistant what happened in plain language and get a confirmation before it records anything." }];
export default function HomePage() { return <main className="min-h-screen overflow-hidden bg-[#f7f9f6]">
  <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Link href="/" className="text-xl font-bold tracking-tight">Business <span className="text-[#16794c]">OS</span></Link><div className="flex items-center gap-3"><Link href="/login" className="hidden px-3 py-2 text-sm font-semibold text-[#526057] sm:block">Sign in</Link><Link href="/signup" className="btn-primary">Start free <ArrowRight size={16}/></Link></div></nav>
  <section className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-12 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-28 lg:pt-20"><div><p className="eyebrow mb-5 flex items-center gap-2"><Sparkles size={14} className="text-[#c78222]"/> Built for ambitious hardware stores</p><h1 className="max-w-2xl text-5xl font-bold leading-[1.04] tracking-[-0.04em] text-[#17211b] sm:text-6xl">Run the store. <span className="text-[#16794c]">Grow the business.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#66736a]">Business OS brings inventory, sales, customers, suppliers and financial clarity into one calm workspace made for the way African businesses work.</p><div className="mt-8 flex flex-wrap items-center gap-3"><Link href="/signup" className="btn-primary px-5 py-3">Create your workspace <ArrowRight size={17}/></Link><Link href="/login" className="btn-secondary px-5 py-3">Sign in</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm text-[#66736a]"><span className="flex items-center gap-2"><Check size={16} className="text-[#16794c]"/> No credit card</span><span className="flex items-center gap-2"><Check size={16} className="text-[#16794c]"/> Set up in minutes</span></div></div><div className="relative"><div className="rounded-2xl border border-[#dce7de] bg-[#e7f4ec] p-4 shadow-[0_24px_60px_rgba(22,121,76,0.12)] sm:p-6"><div className="rounded-xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between border-b border-[#eef1ed] pb-4"><div><p className="text-xs font-semibold text-[#718078]">Monday, 24 June</p><p className="mt-1 text-lg font-bold">Good morning, Amina</p></div><span className="rounded-lg bg-[#e7f4ec] p-2 text-[#16794c]"><Store size={19}/></span></div><div className="grid grid-cols-2 gap-3 py-5"><div className="rounded-lg bg-[#f7f9f6] p-3"><p className="text-xs text-[#718078]">Today&apos;s sales</p><p className="mt-1 text-xl font-bold">KSh 84,620</p><p className="mt-1 text-xs text-[#16794c]">+12.4% this week</p></div><div className="rounded-lg bg-[#f7f9f6] p-3"><p className="text-xs text-[#718078]">Net profit</p><p className="mt-1 text-xl font-bold">KSh 21,480</p><p className="mt-1 text-xs text-[#16794c]">Healthy margin</p></div></div><div className="space-y-3"><div className="flex items-center justify-between text-sm"><span className="font-semibold">Stock health</span><span className="text-xs text-[#c78222]">3 need attention</span></div><div className="h-2 rounded-full bg-[#edf1ed]"><div className="h-2 w-[78%] rounded-full bg-[#16794c]"/></div><div className="flex items-center justify-between rounded-lg border border-[#eef1ed] p-3 text-sm"><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#c78222]"/> Cement 50kg</span><span className="font-semibold">12 bags left</span></div></div></div></div></div></section>
  <section className="border-y border-[#e5e9e4] bg-white"><div className="mx-auto max-w-7xl px-5 py-14 lg:px-8"><div className="mb-8 max-w-xl"><p className="eyebrow mb-2">One operating picture</p><h2 className="text-3xl font-bold tracking-tight">The important things, without the noise.</h2></div><div className="grid gap-5 md:grid-cols-3">{features.map(({icon:Icon,title,text})=><div key={title} className="rounded-xl border border-[#e5e9e4] p-5"><span className="mb-8 inline-flex rounded-lg bg-[#e7f4ec] p-2.5 text-[#16794c]"><Icon size={20}/></span><h3 className="text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#718078]">{text}</p></div>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid gap-8 md:grid-cols-3">{[[ShieldCheck,"Your data stays yours","Every request is scoped to your business. Roles and permissions keep the right people in the right places."],[BarChart3,"Decisions with context","Turn daily activity into useful signals: margin, stock risk, credit exposure and trends."],[Users,"Made for real teams","A fast shared workspace for owners, managers and the people serving customers every day."]].map(([Icon,title,text])=>{const C=Icon as typeof ShieldCheck; return <div key={title as string} className="flex gap-4"><span className="shrink-0 rounded-lg bg-[#fff3df] p-2.5 text-[#b36f16]"><C size={19}/></span><div><h3 className="font-bold">{title as string}</h3><p className="mt-1 text-sm leading-6 text-[#718078]">{text as string}</p></div></div>})}</div></section>
  <footer className="border-t border-[#e5e9e4] bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-7 text-sm text-[#718078] sm:flex-row sm:items-center sm:justify-between lg:px-8"><p>Business OS · the operating system for your next stage.</p><Link href="/signup" className="font-semibold text-[#16794c]">Get started <ArrowRight size={14} className="ml-1 inline"/></Link></div></footer>
</main> }
